######################################## Application ########################################################

appName: mapservice-helm
namespace: app-istio

######################################### configmap #########################################################

configmap:
  name: fastapi2-helm-config
                                  ######### mysql ###########   
  analyseNotificationServiceUrl: notifications-helm.app-istio                                                            
  mysql:
    user: root
    ip: mysql-istio.app-istio
    port: 3306
    password: 1234
    dbname: mapdb

########################################## Image ############################################################

image:
  repository: firaschikhaoui/mapservice
  tag: v1
